// src/app/admin/signup/signup.component.ts
import { NgIf } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-signup',
  standalone: true,
  imports: [ReactiveFormsModule, NgIf],
  templateUrl: './signup.component.html',
  styleUrl: './signup.component.css'
})
export class SignupComponent {
    form: any;
    constructor(private http: HttpClient, private router: Router, ){}
    ngOnInit() {
        this.form = new FormGroup({
            username: new FormControl(),
            email: new FormControl(),
            password: new FormControl()
        })
    }

    onSubmit() {
        this.http.post("http://localhost:3000/register", this.form.value).subscribe((data) => {
            alert("Đăng kí thành công");
            this.router.navigate(['/signin'])
        })
    }
}

<div class="container mx-auto w-75">
    <h1>Sign up</h1>
    <form [formGroup]="form" (submit)="onSubmit()">
        <div class="">
            <label for="" class="form-label">Username</label>
            <input type="text" class="form-control" placeholder="Enter the username" formControlName="username">
            <!-- <div *ngIf="(form.get('username').invalid && form.get('username').dirty) || form.get('username').touched">
                <div *ngIf="form.get('username').errors.required">Username is required</div>
                <div *ngIf="form.get('username').errors.minlength">At least 6 characters</div>
            </div> -->
        </div>
        <div class="">
            <label for="" class="form-label">Email</label>
            <input type="email" class="form-control" placeholder="Enter the email" formControlName="email">
            <!-- <div *ngIf="(form.get('email').invalid && form.get('email').dirty) || form.get('email').touched">
                <div *ngIf="form.get('email').errors.required">Email is required</div>
                <div *ngIf="form.get('email').errors.minLenght">At least 6 characters</div>
            </div> -->
        </div>
        <div class="">
            <label for="" class="form-label">Password</label>
            <input type="password" class="form-control" placeholder="Enter the password" formControlName="password">
        </div>
        <button htmlType="submit" class="btn btn-success mt-3" >Sign up</button>
    </form>
</div>

<!-- [disabled]="form.invalid" -->

// react_vite_b1/src/components/SignUp.jsx
import axios from "axios";
// import React from "react";
import { useForm } from "react-hook-form";
import { useNavigate } from "react-router-dom";

const SignUp = () => {
	const navigate = useNavigate();
	const {
		register,
		handleSubmit,
		reset,
		formState: { errors },
	} = useForm();

	const onSubmit = async (formData) => {
		try {
			reset();
			await axios.post(`${import.meta.env.VITE_API_URL}/signup`, formData);
			alert("Đăng kí thành công");
			navigate("/signin");
		} catch (error) {
			console.log(error);
		}
	};

	return (
		<div className="container w-25 mt-5">
			<h1>Đăng kí tài khoản</h1>
			<form onSubmit={handleSubmit(onSubmit)}>
				<div className="mb-3">
					<label htmlFor="" className="form-label">
						Email
					</label>
					<input
						type="email"
						className="form-control"
						{...register("email", {
							required: "Bắt buộc nhập",
							pattern: {
								value: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
								message: "Email không đúng định dạng",
							},
						})}
					/>
					{errors.email && <p className="text-danger">{errors.email.message}</p>}
				</div>
				<div className="mb-3">
					<label htmlFor="" className="form-label">
						Mật khẩu
					</label>
					<input
						type="password"
						className="form-control"
						{...register("password", {
							required: "Bắt buộc nhập",
							minLength: { value: 6, message: "Nhập ít nhất 6 kí tự" },
						})}
					/>
					{errors.password && <p className="text-danger">{errors.password.message}</p>}
				</div>
				<button className="btn btn-primary" type="submit">
					Đăng kí
				</button>
			</form>
		</div>
	);
};

export default SignUp;
